export const INITIAL_DISHES = [
  {
    "name": "Salmón a la naranja",
    "ingredients": ["369884bd-7505-4e57-870d-34bc547f3e5f"],
    "type": "LAUNCH",
    "description": "Un delicioso plato de salmón con salsa de naranja.",
    "recipe": "1. Marinar el salmón en jugo de naranja y ajo.\n2. Asar el salmón a la parrilla.\n3. Preparar la salsa de naranja con ralladura de naranja y azúcar.\n4. Verter la salsa sobre el salmón y servir.",
  },
  {
    "name": "Pollo al curry",
    "ingredients": ["d6c9d587-1c5e-48ab-ae78-92fc47b35f71"],
    "type": "LAUNCH",
    "description": "Un plato sabroso de pollo con una mezcla de curry.",
    "recipe": "1. Dorar el pollo en una sartén.\n2. Preparar la salsa de curry con leche de coco y especias.\n3. Cocinar el pollo en la salsa hasta que esté tierno.\n4. Servir caliente.",
  },
  {
    "name": "Ensalada de aguacate",
    "ingredients": ["9a81809f-5566-4521-964a-0c957f1b8f56"],
    "type": "LAUNCH",
    "description": "Una refrescante ensalada de aguacate con tomate y cilantro.",
    "recipe": "1. Cortar el aguacate y el tomate en cubos.\n2. Mezclar con cilantro picado y aderezar con limón y sal.\n3. Servir como acompañamiento.",
  },
  {
    "name": "Brócoli con queso",
    "ingredients": ["7e0e77c0-0b42-4ff6-9d76-5512e0e631a6"],
    "type": "LAUNCH",
    "description": "Brócoli fresco cubierto con queso derretido y especias.",
    "recipe": "1. Cocinar el brócoli al vapor hasta que esté tierno.\n2. Cubrir con queso cheddar derretido.\n3. Espolvorear con pimienta negra y servir caliente.",
  },
  {
    "name": "Tomate relleno",
    "ingredients": ["a9ab078a-0570-416f-943f-42f38f9c94e2"],
    "type": "LAUNCH",
    "description": "Tomates maduros rellenos de una mezcla de carne picada y arroz.",
    "recipe": "1. Vaciar los tomates y rellenar con una mezcla de carne picada, arroz y especias.\n2. Hornear hasta que los tomates estén tiernos.\n3. Servir como plato principal.",
  },
  {
    "name": "Cebolla caramelizada",
    "ingredients": ["bba1bceb-8a32-4ec7-ae49-206fe8b91e36"],
    "type": "LAUNCH",
    "description": "Cebolla caramelizada con azúcar y balsámico.",
    "recipe": "1. Cortar la cebolla en rodajas finas.\n2. Cocinar a fuego lento con azúcar y vinagre balsámico hasta que esté caramelizada.\n3. Servir como acompañamiento.",
  },
  {
    "name": "Zanahorias glaseadas",
    "ingredients": ["f4517c2d-98c3-4d13-91db-c9e90e2e409f"],
    "type": "LAUNCH",
    "description": "Zanahorias glaseadas con miel y mantequilla.",
    "recipe": "1. Cocinar las zanahorias en agua hasta que estén tiernas.\n2. Glasear con una mezcla de miel y mantequilla.\n3. Servir como acompañamiento.",
  },
  {
    "name": "Papa asada",
    "ingredients": ["e9d086dd-4cf0-4f06-8493-cc4c9e59f3dd"],
    "type": "LAUNCH",
    "description": "Papas asadas con aceite de oliva y romero.",
    "recipe": "1. Cortar las papas en gajos y mezclar con aceite de oliva y romero.\n2. Asar en el horno hasta que estén doradas y crujientes.\n3. Servir como acompañamiento.",
  },
  {
    "name": "Ajo al horno",
    "ingredients": ["0b96d261-5254-4e05-8c1e-4d9328d7de3f"],
    "type": "LAUNCH",
    "description": "Cabezas de ajo asadas con aceite de oliva y hierbas.",
    "recipe": "1. Cortar la parte superior de las cabezas de ajo para exponer los dientes.\n2. Rociar con aceite de oliva y hierbas.\n3. Asar en el horno hasta que estén tiernas y doradas.\n4. Servir como acompañamiento.",
  },
  {
    "name": "Cilantro",
    "ingredients": ["2a24561a-0c0f-4b88-b186-d8aa8a7d09ca"],
    "type": "LAUNCH",
    "description": "Cilantro fresco para dar sabor a tus platos.",
    "recipe": "",
  },
  {
    "name": "Canela",
    "ingredients": ["efb3ed92-7c16-44a2-94e6-e0e92b4a53b2"],
    "type": "LAUNCH",
    "description": "Canela en polvo para dar sabor a tus postres.",
    "recipe": "",
  },
  {
    "name": "Limón",
    "ingredients": ["c795ad9d-17a2-40e7-8ec2-145e7d862bb7"],
    "type": "LAUNCH",
    "description": "Limones frescos para dar sabor y acidez a tus platos.",
    "recipe": "",
  }];